// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PearlMetric.GatewayApi.Data;

#nullable disable

namespace GatewayApi.Migrations
{
    [DbContext(typeof(PearlMetricDb))]
    [Migration("20260723025156_HardenDomainInvariants")]
    partial class HardenDomainInvariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.CalibrationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlignmentMatrixJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CalibratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CalibrationReferenceValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId")
                        .IsUnique();

                    b.ToTable("CalibrationProfiles");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ColorMetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("A")
                        .HasColumnType("double precision");

                    b.Property<double>("B")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<double>("DeltaE")
                        .HasColumnType("double precision");

                    b.Property<double>("L")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ShadeGuideValue")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId", "SequenceIndex")
                        .IsUnique();

                    b.ToTable("ColorMetricSamples", t =>
                        {
                            t.HasCheckConstraint("CK_ColorMetricSamples_A", "\"A\" >= -128 AND \"A\" <= 128");

                            t.HasCheckConstraint("CK_ColorMetricSamples_B", "\"B\" >= -128 AND \"B\" <= 128");

                            t.HasCheckConstraint("CK_ColorMetricSamples_ConfidenceScore", "\"ConfidenceScore\" >= 0 AND \"ConfidenceScore\" <= 1");

                            t.HasCheckConstraint("CK_ColorMetricSamples_DeltaE", "\"DeltaE\" >= 0");

                            t.HasCheckConstraint("CK_ColorMetricSamples_L", "\"L\" >= 0 AND \"L\" <= 100");

                            t.HasCheckConstraint("CK_ColorMetricSamples_SequenceIndex", "\"SequenceIndex\" >= 0");
                        });
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ScanFrame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("integer");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("StorageKey")
                        .IsUnique();

                    b.HasIndex("ScanRunId", "SequenceIndex")
                        .IsUnique();

                    b.ToTable("Frames", t =>
                        {
                            t.HasCheckConstraint("CK_Frames_ByteSize", "\"ByteSize\" > 0");

                            t.HasCheckConstraint("CK_Frames_SequenceIndex", "\"SequenceIndex\" >= 0");
                        });
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlgorithmVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("BaselineScanRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeltaEFormula")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("RegimenId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaselineScanRunId");

                    b.HasIndex("RegimenId", "CapturedAtUtc");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.WhiteningRegimen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ScheduledIntervalHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Regimens", t =>
                        {
                            t.HasCheckConstraint("CK_Regimens_DurationDays", "\"DurationDays\" > 0");

                            t.HasCheckConstraint("CK_Regimens_ScheduledIntervalHours", "\"ScheduledIntervalHours\" > 0");
                        });
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.CalibrationProfile", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.ScanRun", "ScanRun")
                        .WithOne("Calibration")
                        .HasForeignKey("PearlMetric.GatewayApi.Models.CalibrationProfile", "ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ColorMetricSample", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.ScanRun", "ScanRun")
                        .WithMany("Samples")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ScanFrame", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.ScanRun", "ScanRun")
                        .WithMany("Frames")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ScanRun", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.ScanRun", "BaselineScanRun")
                        .WithMany()
                        .HasForeignKey("BaselineScanRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PearlMetric.GatewayApi.Models.WhiteningRegimen", "Regimen")
                        .WithMany("Runs")
                        .HasForeignKey("RegimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaselineScanRun");

                    b.Navigation("Regimen");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.WhiteningRegimen", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.Patient", "Patient")
                        .WithMany("Regimens")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.Patient", b =>
                {
                    b.Navigation("Regimens");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ScanRun", b =>
                {
                    b.Navigation("Calibration");

                    b.Navigation("Frames");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.WhiteningRegimen", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
